# PORTS
# Minio      : 9000
# PG_Mlflow  : 5432
# MLFlow     : 5000
# PG_Airflow : 5433
# Redis      : 6379
# Airflow    : 8080
# Flower     : 5555
#

services:
  # ===================
  # MLFlow
  # ===================
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - "BACKEND_URI=postgresql://mlflow:mlflow_pass@postgres:5432"
      - "MLFLOW_S3_ENDPOINT_URL=http://minio:9000"
      - "ARTIFACT_ROOT=minio://mlflow-artifacts/"
      - "AWS_ACCESS_KEY_ID=mlflow_access_key"
      - "AWS_SECRET_ACCESS_KEY=mlflow_secret_key"
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio:latest
    ports:
     - "9000:9000"
     - "9001:9001"
    environment:
      - "MINIO_ACCESS_KEY=mlflow_access_key"
      - "MINIO_SECRET_KEY=mlflow_secret_key"
    volumes:
      - ./mlflow/minio:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=mlflow"
      - "POSTGRES_PASSWORD=mlflow_pass"
    volumes:
      - ./mlflow/postgres:/var/lib/postgresql/data

  # ====================
  # Airflow
  # ====================
#  airflow:
#    build:
#      context: ./airflow
#      dockerfile: Dockerfile
#    container_name: airflow
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mlflow
#    volumes:
#      - ./airflow/airflow_env/artifacts:/tmp/airflow/artifacts/
#      - ./mlflow/artifacts:/mlflow/artifacts
#      - ./airflow/dags:/opt/airflow/dags
#    command: standalone
