[tool.poetry]
name = "platescanner"
version = "0.3.0"
description = ""
authors = [
    "Maksim Shushkevich <m.e.shushkevich@yandex.com>",
    "Pavel Lekomtsev <example@of.com>",
    "Vladislav Tyurin <example@of.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
ultralytics = ">=8.3.30"
clearml = "^1.16.4"
albumentations = "^1.4.10"
nodeflow = "0.1.1"
pycocotools = "^2.0.8"
shapely = "^2.0.6"
torch = {version = "^2.6.0+cu124", source = "pytorch-gpu"}
torchvision = {version = "^0.21.0+cu124", source = "pytorch-gpu"}
paddleocr = "^2.9.1"
paddlepaddle = "^2.6.2"
cvtk = { git = "https://github.com/encore-ecosystem/CVTK.git" }

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
platescanner = "platescanner.main:main"
